apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
  # annotations:
  #   volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  # storageClassName: default
  # accessModes:
  #   - ReadWriteOnce
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqldata
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/sqldata"
